###
GET http://localhost:3000/

###
GET http://127.0.0.1:3000/

###


###
GET http://localhost:3000/

###
GET http://localhost:3000/api/v1/users/1

###
GET http://localhost:3000/api/v1/users/search/sally

###

GET http://localhost:3000/api/v1/users/search/password/0
