###
@port = 3070

###
GET http://localhost:3070/

###
GET http://127.0.0.1:3070/

###


###
GET http://localhost:3070/

###
GET http://localhost:3070/api/v1/users/1

###
GET http://localhost:3070/api/v1/users/search/sally

###

GET http://localhost:300/api/v1/users/search/password/0

###

POST http://localhost:3070/api/v1/users/seed

###
POST http://localhost:3070/api/v1/users/login

###

###
GET http://localhost:3070/api/v1/users

###
POST http://localhost:3070/api/v1/users/login
Content-Type: application/json

{
    "email": "tom@email.com",
    "password": "1"

}